FROM ubuntu:xenial
RUN apt update
RUN apt install -y phing git
RUN apt install -y bzr-builddeb dh-make rpm
RUN apt install -y composer php-mbstring
RUN apt install -y sudo
RUN apt install -y wget curl
